#!/bin/bash


# Variables (edit these as needed)
USERNAME=$1
PASSWORD=$2
DATABASE_NAME=$3

# Run PostgreSQL commands
sudo -u postgres psql <<EOF
CREATE USER $USERNAME WITH PASSWORD '$PASSWORD';
CREATE DATABASE $DATABASE_NAME;
GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $USERNAME;
ALTER USER $USERNAME WITH SUPERUSER;
EOF
