# HTTP redirect to HTTPS
server {
    listen 80;
    server_name lovegood.in www.lovegood.in;
    return 301 https://$host$request_uri;
}

# HTTPS server block
server {

    # SSL certificates
    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/lovegood.in/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/lovegood.in/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


    # Root directory for the site
    root /var/www/html;
    index index.html index.htm;

    # Logging
    access_log /var/log/nginx/lovegood.in.access.log;
    error_log /var/log/nginx/lovegood.in.error.log;

    # Default location block
    location / {
        try_files $uri $uri/ index.html;
    }

}
